---
title: "Results2"
format: html
editor: visual
---

# CXCL12 Expression and Abundance (Figure 2)

## Libraries and Data Files

```{r}
#clear environment
rm(list=ls())
```

Libraries:

```{r}
#libraries
library(data.table)
library(tidyverse)
library(ggpubr)
library(ggforce)
library(ggthemes)
```

Plot theme:

```{r}
source("/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/theme_manuscript.R")
```

Directories:

```{r}
#resources directory
dir.resources <- "/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Data/"

# data files required
file.singlecells <- paste0(dir.resources, "filt.cells.csv")
file.rna <- paste0(dir.resources, "filt.rna.csv")
file.clinical <- paste0(dir.resources, "filt.clinical.csv")
```

File loading:

```{r}
#cells file
cells <- fread(file.singlecells)

#clinical data file
clinical <- fread(file.clinical)
clinical <- clinical %>%
    mutate(IntClust = str_remove_all(IntClust, "IntClust ")) #removing "IntClust" from the IntClust column

#rna file
rna <- read.table(file.rna,row.names=1,header = T,sep=",")
colnames(rna) <- gsub("\\.", "-", colnames(rna)) #changing sample ids to match all other data
rna <- t(rna) #samples as colnames
```

## RNA Expressions

### CXCL12

```{r}
#adding intclust classification
rna.ic <- merge(rna,clinical[,c("metabric_id","IntClust")],by.x=0,by.y="metabric_id")

#plotting cxcl12 expression in ic10 vs. ic4-

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcl12.rna.pdf")

ggplot(rna.ic,mapping=aes(x=IntClust,y=CXCL12)) +
  theme_manuscript() +
  geom_boxplot(aes(color=IntClust,fill=IntClust),show.legend = F,outliers = F)+
  geom_jitter(aes(color=IntClust),show.legend = F,width=0.2)+
  scale_fill_manual(values=c("#7D26CD","#B5D0D2")) +
  scale_color_manual(values=c("black","black")) +
  stat_compare_means(method = "wilcox.test",size=7,label.x.npc=0.3,label = "p.format") +
  ylab("CXCL12 RNA expression")

dev.off()
```

### CXCR7

```{r}
#plotting cxcr7 expression in ic10 vs. ic4-

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcr7.rna.pdf")

ggplot(rna.ic,mapping=aes(x=IntClust,y=ACKR3)) +
  theme_manuscript()+
  geom_boxplot(aes(color=IntClust,fill=IntClust),show.legend = F,outliers = F)+
  geom_jitter(aes(color=IntClust),show.legend = F,width=0.2)+
  scale_fill_manual(values=c("#7D26CD","#B5D0D2")) +
  scale_color_manual(values=c("black","black")) +
  stat_compare_means(method = "wilcox.test",size=7,label.x.npc=0.3,label = "p.format") +
  ylab("CXCR7 RNA expression")

dev.off()
```

### CXCR4

```{r}
#plotting cxcr4 expression in ic10 vs. ic4-

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcr4.rna.pdf")

ggplot(rna.ic,mapping=aes(x=IntClust,y=CXCR4)) +
  theme_manuscript()+
  geom_boxplot(aes(color=IntClust,fill=IntClust),show.legend = F,outliers = F)+
  geom_jitter(aes(color=IntClust),show.legend = F,width=0.2)+
  scale_fill_manual(values=c("#7D26CD","#B5D0D2")) +
  scale_color_manual(values=c("black","black")) +
  stat_compare_means(method = "wilcox.test",size=7,label.x.npc=0.3,label = "p.format") +
  ylab("CXCR4 RNA expression")

dev.off()
```

## Correlations

### CXCL12 vs. CXCR7

```{r}
#plot cxcr7 expression vs. cxcl12 expression

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcr7.cxcl12.pdf",width = 11)

ggplot(rna.ic,aes(x=CXCL12,y=ACKR3)) +
  theme_manuscript()+
  geom_point(aes(color=IntClust),size=3)+
  scale_color_manual(values=c("#7D26CD","#B5D0D2")) +
  stat_cor(method="spearman",aes(label = paste(after_stat(rr.label))),size=7) +
  stat_cor(method="spearman",aes(label = paste(after_stat(p.label))), label.y.npc = 0.87,size=7) +
  geom_smooth(method='lm', formula= y~x,linewidth=0.6,color="black") +
  xlab("CXCL12 RNA expression") +
  ylab("CXCR7 RNA expression") +
  facet_wrap(~IntClust)

dev.off()
```

### CXCL12 vs. CXCR4

```{r}
#plot cxcr4 expression vs. cxcl12 expression

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcr4.cxcl12.pdf",width = 11)

ggplot(rna.ic,aes(x=CXCL12,y=CXCR4)) +
  theme_manuscript()+
  geom_point(aes(color=IntClust),size=3)+
  scale_color_manual(values=c("#7D26CD","#B5D0D2")) +
  stat_cor(method="spearman",aes(label = paste(after_stat(rr.label))),size=7) +
  stat_cor(method="spearman",aes(label = paste(after_stat(p.label))), label.y.npc = 0.87,size=7) +
  geom_smooth(method='lm', formula= y~x,linewidth=0.6,color="black") +
  xlab("CXCL12 RNA expression") +
  ylab("CXCR4 RNA expression") +
  facet_wrap(~IntClust)

dev.off()
```

## CXCL12 Protein Abundance

### Tumour vs. TME Cells

```{r}
#looking at cxcl12 protein abundance in tumour cells vs. tme cells

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Supplementary/cxcl12.tum.tme.pdf",width=4)

ggplot(cells,aes(x=factor(is_epithelial),y=asinh(CXCL12))) +
  theme_manuscript() +
  geom_boxplot(aes(color=factor(is_epithelial),fill=factor(is_epithelial)),show.legend = F) +
  scale_color_manual(values=c("black","black")) +
  scale_fill_manual(values=c("#0072B2","#E69F00")) +
  stat_compare_means(method = "wilcox.test",label.x.npc="middle",label="p.format",size=6) +
  guides(color="none") +
  ylab("CXCL12 mean abundance (arsinh)") +
  xlab("Cell type") +
  scale_x_discrete(labels=c("TME","Tumour"))

dev.off()
```

### Abundance in Tumour Cells

```{r}
#taking cxcl12 abundance of epi only and sample ids
abund.epi <- cells[cells$is_epithelial == 1, c("metabric_id", "CXCL12")]

#calculating the mean intensity for each sample
abund.epi <-
  aggregate(abund.epi$CXCL12, list(abund.epi$metabric_id), FUN = mean)

colnames(abund.epi) <- c("metabric_id", "cxcl12_abund")

#adding intclust classifications
abund.epi <- merge(clinical[,c("metabric_id","IntClust")],abund.epi,by="metabric_id")

#plotting cxcl12 abundance in tumour cells between ic10 and ic4-

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcl12.abund.epi.pdf")

ggplot(abund.epi,aes(x=IntClust,y=asinh(cxcl12_abund))) +
  theme_manuscript() +
  geom_boxplot(aes(color=IntClust,fill=IntClust),show.legend = F,outliers = F)+
  geom_jitter(aes(color=IntClust),show.legend = F,width=0.2)+
  scale_fill_manual(values=c("#7D26CD","#B5D0D2")) +
  scale_color_manual(values=c("black","black")) +
  stat_compare_means(method = "wilcox.test",size=7,label.x.npc="middle",label = "p.format") +
  ylab("CXCL12 mean abundance (arsinh)")

dev.off()
```

### Abundance vs. Expression

Epithelial cells only:

```{r}
#merging cxcl12 expression and abundance data into one df
abund.rna <- merge(rna[,c("CXCL12","CXCR4")],abund.epi,by.x=0,by.y="metabric_id")

#plotting cxcl12 expression vs. cxcl12 abundance

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Figure2/cxcl12.abund.rna.pdf")

ggplot(abund.rna,aes(x=CXCL12,y=asinh(cxcl12_abund))) +
  theme_manuscript()+
  geom_point(aes(color=IntClust),size=3) +
  scale_color_manual(values=c("#7D26CD","#B5D0D2")) +
  stat_cor(method="spearman",aes(label = paste(after_stat(rr.label))),size=7) +
  stat_cor(method="spearman",aes(label = paste(after_stat(p.label))), label.y.npc = 0.87,size=7) +
  geom_smooth(method='lm', formula= y~x,linewidth=0.6,color="black") +
  ylab("CXCL12 mean abundance (arsinh)") +
  xlab("CXCL12 RNA expression")

dev.off()
```

All cells:

```{r}
#taking sample ids and cxcl12 abundance of all cells
abund.all <- cells[,c("metabric_id","CXCL12")]

#mean abundance per sample
abund.all <-  
  aggregate(abund.all$CXCL12, list(abund.all$metabric_id), FUN = mean)

#merging cxcl12 expression and abundance data into one df
abund.all.rna <- merge(rna[,c("CXCL12","CXCR4")],abund.all,by.x=0,by.y="Group.1")

colnames(abund.all.rna) <- c("metabric_id","CXCL12","CXCR4","cxcl12_abund")

#adding intclust classifications
abund.all.rna <- merge(clinical[,c("metabric_id","IntClust")],abund.all.rna,by="metabric_id")

#plotting cxcl12 expression vs. cxcl12 abundance

pdf(file="/Users/aphuong/Library/CloudStorage/OneDrive-SharedLibraries-TheInstituteofCancerResearch/Stephen-John Sammut - IMC-networks/Thesis_Code/Plots/Supplementary/cxcl12.abund.all.rna.pdf")

ggplot(abund.all.rna,aes(x=CXCL12,y=asinh(cxcl12_abund))) +
  theme_manuscript()+
  geom_point(aes(color=IntClust),size=3) +
  scale_color_manual(values=c("#7D26CD","#B5D0D2")) +
  stat_cor(method="spearman",aes(label = paste(after_stat(rr.label))),size=7) +
  stat_cor(method="spearman",aes(label = paste(after_stat(p.label))), label.y.npc = 0.87,size=7) +
  geom_smooth(method='lm', formula= y~x,linewidth=0.6,color="black") +
  ylab("CXCL12 mean abundance (arsinh)") +
  xlab("CXCL12 RNA expression")

dev.off()
```
